import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import HandAnimated from './components/HandAnimated'



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        {children}
        <HandAnimated></HandAnimated>
      </body>
    </html>
  );
}
